# Generated by Django 5.1.3 on 2024-11-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='tiempo_defensa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='tiempo_otorgado',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='tiempo_pregunta',
            field=models.IntegerField(),
        ),
    ]
