# Generated by Django 5.1.3 on 2024-11-12 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0002_alter_monografia_tiempo_defensa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesormonografia',
            name='monografia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='Register.monografia'),
        ),
    ]
