# Generated by Django 5.1.3 on 2024-11-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_alter_profesormonografia_monografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='monografia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='monografias/'),
        ),
    ]
