# Generated by Django 5.1.3 on 2024-11-20 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0004_monografia_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monografia',
            name='archivo',
        ),
    ]
